steps:
  - id: DockerImageビルドa
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/devtest-cloudrund-handson/my-first-image:develop", "."]
  - id: 単体テスト(まだstepだけ)
    name: "gcr.io/cloud-builders/docker"
  - id: ContainerRegistryへPush
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/devtest-cloudrund-handson/my-first-image:develop"]
  - id: CloudRunへデプロイ(dev)
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "my-first-image-dev",
        "--image",
        "gcr.io/devtest-cloudrund-handson/my-first-image:develop",
        "--region",
        asia-northeast1,
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images: ["gcr.io/devtest-cloudrund-handson/my-first-image"]
