steps:
  - id: DockerImageビルド
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/devtest-cloudrund-handson/my-first-image", "."]
  - id: ContainerRegistryへPush
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/devtest-cloudrund-handson/my-first-image"]
images: ["gcr.io/devtest-cloudrund-handson/my-first-image"]
