steps:
  - id: ContainerRegistryからPull
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "gcr.io/devtest-cloudrund-handson/my-first-image:develop"]
  - id: 再び単体テスト？
    name: "gcr.io/cloud-builders/docker"
  - id: CloudRunへデプロイ(staging)
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "my-first-image-staging",
        "--image",
        "gcr.io/devtest-cloudrund-handson/my-first-image",
        "--region",
        asia-northeast1,
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]