steps:
  - id: ContainerRegistryからPulla
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "gcr.io/devtest-cloudrund-handson/my-first-image:develop"]
  - id: CloudRunへデプロイ(staging)dayo
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "my-first-image-staging",
        "--image",
        "gcr.io/devtest-cloudrund-handson/my-first-image:develop",
        "--region",
        asia-northeast1,
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
  - id: stagingのタグ付
    name: "gcr.io/cloud-builders/docker"
    args: ["tag",
    "gcr.io/devtest-cloudrund-handson/my-first-image:develop",
    "gcr.io/devtest-cloudrund-handson/my-first-image:staging"]
images: ["gcr.io/devtest-cloudrund-handson/my-first-image:staging"]